# Generated by Django 4.0.6 on 2022-07-23 01:55

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_vm', models.CharField(max_length=35)),
                ('ip', models.CharField(max_length=35)),
            ],
        ),
        migrations.CreateModel(
            name='Robo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('nome_alternativo', models.CharField(max_length=100)),
                ('hora_execucao', models.DateTimeField(default=datetime.datetime.now)),
                ('status', models.CharField(choices=[('OPERACIONAL', 'OPERACIONAL'), ('EXECUTANDO', 'EXECUTANDO'), ('CONCLUÍDO', 'CONCLUÍDO'), ('FALHA', 'FALHA'), ('DESATIVADO', 'DESATIVADO')], default='OPERACIONAL', max_length=200)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='auth.group')),
                ('vm', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pages.vm')),
            ],
        ),
    ]
